var searchData=
[
  ['creating_20dfu_20images',['Creating DFU images',['../background_dfu_firmware_image.html',1,'lib_background_dfu']]],
  ['cycling_20speed_20and_20cadence_20application',['Cycling Speed and Cadence Application',['../ble_sdk_app_csc.html',1,'examples_ble_peripheral']]],
  ['current_20time_20application',['Current Time Application',['../ble_sdk_app_cts_c.html',1,'examples_ble_peripheral']]],
  ['command_20line_20interface_20_28cli_29_20example',['Command Line Interface (CLI) Example',['../cli_example.html',1,'examples_hw_peripheral_devices']]],
  ['cryptographic_20examples',['Cryptographic examples',['../crypto_examples.html',1,'examples']]],
  ['cryptocell_20integration_20tests',['CryptoCell Integration Tests',['../cryptocell_example.html',1,'crypto_examples_external']]],
  ['capacitive_20sensor_20low_2dlevel_20example',['Capacitive Sensor Low-level Example',['../csense_example.html',1,'examples_hw_peripheral_devices']]],
  ['compiling_20and_20running_20a_20first_20example',['Compiling and running a first example',['../getting_started_examples.html',1,'nrf51_getting_started']]],
  ['compiling_20and_20running_20an_20example_20from_20the_20qspi_20using_20xip',['Compiling and running an example from the QSPI using XiP',['../getting_started_qspi.html',1,'getting_started_examples']]],
  ['clock',['Clock',['../hardware_driver_clock.html',1,'hardware_drivers_desc']]],
  ['comp',['COMP',['../hardware_driver_comp.html',1,'hardware_drivers_desc']]],
  ['commissioning',['Commissioning',['../iot_commissioning_top.html',1,'iot_getting_started']]],
  ['connectivity_20scenarios',['Connectivity scenarios',['../iot_connectivity.html',1,'iot_intro']]],
  ['coap',['CoAP',['../iot_sdk_app_coap.html',1,'iot_examples']]],
  ['client',['Client',['../iot_sdk_app_coap_client.html',1,'iot_sdk_app_coap']]],
  ['client',['Client',['../iot_sdk_app_dtls_coap_client.html',1,'iot_sdk_app_dtls']]],
  ['client',['Client',['../iot_sdk_app_ipv6_stack_udp_client.html',1,'iot_sdk_app_ipv6_stack_udp_client_server']]],
  ['client',['Client',['../iot_sdk_app_lwip_tcp_client.html',1,'iot_sdk_app_lwip_tcp']]],
  ['client',['Client',['../iot_sdk_app_lwip_udp_client.html',1,'iot_sdk_app_lwip_udp_client_server']]],
  ['compiling_20openssl',['Compiling OpenSSL',['../iot_sdk_user_guides_compiling_openssl.html',1,'iot_getting_started']]],
  ['creating_20link_2dlocal_20ipv6_20addresses',['Creating link-local IPv6 addresses',['../iot_sdk_user_guides_ipv6_address_creation.html',1,'iot_ug_border_router']]],
  ['connecting_20devices_20to_20the_20router',['Connecting devices to the router',['../iot_sdk_user_guides_linux_commands.html',1,'iot_ug_border_router']]],
  ['connection_20parameters_20negotiation',['Connection Parameters Negotiation',['../lib_ble_conn_params.html',1,'lib_ble']]],
  ['connection_20state',['Connection state',['../lib_ble_conn_state.html',1,'lib_ble']]],
  ['command_20line_20interface_20library',['Command Line Interface library',['../lib_cli.html',1,'general_libraries']]],
  ['cryptography_20library_20_2d_20nrf_5fcrypto',['Cryptography library - nrf_crypto',['../lib_crypto.html',1,'general_libraries']]],
  ['cifra_20backend',['Cifra backend',['../lib_crypto_backend_cifra.html',1,'lib_crypto_backends']]],
  ['chacha_2dpoly',['ChaCha-Poly',['../lib_crypto_chacha_poly.html',1,'lib_crypto_frontends']]],
  ['cli_20example',['CLI Example',['../lib_crypto_cli_example.html',1,'crypto_examples_nrf_crypto']]],
  ['configuring_20nrf_5fcrypto_20frontend_20and_20backends',['Configuring nrf_crypto frontend and backends',['../lib_crypto_config.html',1,'lib_crypto']]],
  ['capacitive_20sensor_20library',['Capacitive Sensor library',['../lib_csense.html',1,'general_libraries']]],
  ['capacitive_20sensor_20library_20example',['Capacitive Sensor Library Example',['../lib_csense_example.html',1,'examples_hw_peripheral_devices']]],
  ['capacitive_20sensor_20low_2dlevel_20library',['Capacitive Sensor low-level library',['../lib_csense_lowlevel.html',1,'general_libraries']]],
  ['coap',['CoAP',['../lib_iot_coap.html',1,'lib_iot_experimental']]],
  ['coap_20addons',['CoAP addons',['../lib_iot_coap_addon.html',1,'lib_iot_coap']]],
  ['coap_20block',['CoAP Block',['../lib_iot_coap_addon_block.html',1,'lib_iot_coap_addon']]],
  ['coap_20observe',['CoAP Observe',['../lib_iot_coap_addon_observe.html',1,'lib_iot_coap_addon']]],
  ['coap_20client_2fserver',['CoAP client/server',['../lib_iot_coap_core.html',1,'lib_iot_coap']]],
  ['commissioning',['Commissioning',['../lib_iot_commissioning.html',1,'lib_iot_experimental']]],
  ['context_20manager',['Context Manager',['../lib_iot_context_manager.html',1,'lib_iot_experimental']]],
  ['configurable_20string_20descriptor_20module',['Configurable string descriptor module',['../lib_usbd_string_desc.html',1,'lib_usbd']]],
  ['custom_20message_20generation',['Custom message generation',['../nfc_ndef_message_module_dox.html',1,'nfc_ndef_generation_dox']]],
  ['capability_20container_20file_20parser',['Capability Container file parser',['../nfc_t4t_cc_parser_dox.html',1,'nfc_t4t_hl_detection_procedures_dox']]],
  ['command_20set',['Command set',['../nfc_type2tag_commands_dox.html',1,'nfc_type2tag_dox']]],
  ['cryptocell_20nrf_5fcc310_5fbl_20library_20integration_20tests',['CryptoCell nrf_cc310_bl Library Integration Tests',['../nrf_cc310_bl_example.html',1,'crypto_examples_external']]],
  ['chacha_2dpoly_20example',['ChaCha-Poly Example',['../nrf_crypto_chacha_poly_example.html',1,'crypto_examples_nrf_crypto']]],
  ['cycling_20speed_20and_20cadence_20service',['Cycling Speed and Cadence Service',['../service_cycling_speed_and_cad.html',1,'ble_services']]]
];
